include:
  - project: 'fixers/cicd'
    file: '.gitlab-ci-fixers-base.yml'
  - project: 'fixers/cicd'
    file: '.gitlab-ci-fixers-libs.yml'
  - project: 'fixers/cicd'
    file: '.gitlab-ci-fixers-docs.yml'
