ssm:
  signer:
    user:
      name: adam
      key: user/adam
    admin:
      name: ssm-admin
      key: user/adam
  couchdb:
    url: http://localhost:5984
    username: couchdb
    password: couchdb
    serviceName: ssm-couchdb-unit
  chaincode:
    url: http://localhost:9090

---
spring:
  config:
    activate:
      on-profile: gitlab
ssm:
  signer:
    user:
      name: ssm-agent
      key: ${COMMUNE_SSM_AGENT}
    admin:
      name: ssm-agent
      key:  ${COMMUNE_SSM_AGENT}
  couchdb:
    url: http://peer0.pr-commune.smartb.network:5984
    username: ${COMMUNE_COUCHDB_USERNAME}
    password: ${COMMUNE_COUCHDB_PASSWORD}
    serviceName: ssm-couchdb-unit
  chaincode:
    url: http://peer0.pr-commune.smartb.network
